@startuml 
digraph G {
 concentrate=true 
C -> A;
C -> D;
C -> B;
A -> C;
A -> D;
A -> B;
D [color=red]D -> C;
D -> A;
D -> B;
B [color=red]B -> C;
B -> A;
B -> D;
C -> A;
A -> D;
A -> B;
A -> C;
} 
 @enduml